### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by skariel** [theindiepocalypse/and-this-last-one#1]

**Comment by theindiepocalypse** [comment]
@skariel:

Thanks for creating this issue

**Comment by skariel** [comment]
@theindiepocalypse list owners /

**Comment by theindiepocalypse** [comment]
@skariel:



such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse list owners /

**Comment by theindiepocalypse** [comment]
@skariel 

such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse list owners /

**Comment by theindiepocalypse** [comment]
@skariel 

such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse list owners /

**Comment by theindiepocalypse** [comment]
@skariel 

Owner | Percent
-------|---------
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse hi/

**Comment by theindiepocalypse** [comment]
@skariel 

such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse list owners /

**Comment by theindiepocalypse** [comment]
@skariel 

such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse list owners /

**Comment by theindiepocalypse** [comment]
@skariel 

such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse list owners /

**Comment by theindiepocalypse** [comment]
@skariel 

Owner | Percent
-------|---------
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse hi/

**Comment by theindiepocalypse** [comment]
@skariel 

hi!

**Comment by skariel** [comment]
@theindiepocalypse merge/

**Comment by theindiepocalypse** [comment]
@skariel 

merging commands are allowed only on pull requests, nothing to merge here :)

**Comment by skariel** [comment]
@theindiepocalypse hi/

**Comment by theindiepocalypse** [comment]
@skariel hi!

**Comment by skariel** [comment]
@theindiepocalypse list  owners/

**Comment by theindiepocalypse** [comment]
@skariel such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse list owners  /

**Comment by theindiepocalypse** [comment]
@skariel 

Owner | Percent
-------|---------
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse list owners/

**Comment by theindiepocalypse** [comment]
@skariel 

Owner | Percent
-------|---------
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse        merge/

**Comment by theindiepocalypse** [comment]
@skariel merging commands are allowed only on pull requests, nothing to merge here :)

**Comment by skariel** [comment]
@theindiepocalypse    hi/

**Comment by theindiepocalypse** [comment]
@skariel hi!

**Comment by skariel** [comment]
@theindiepocalypse    list             owners/

**Comment by theindiepocalypse** [comment]
@skariel such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse            list                               owners /

**Comment by theindiepocalypse** [comment]
@skariel 

Owner | Percent
-------|---------
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse             list                   owners/

**Comment by theindiepocalypse** [comment]
@skariel 

Owner | Percent
-------|---------
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse hi/

**Comment by theindiepocalypse** [comment]
@skariel hi!

**Comment by skariel** [comment]
@theindiepocalypse                              merge                    /

**Comment by theindiepocalypse** [comment]
@skariel merging commands are allowed only on pull requests, nothing to merge here :)

**Comment by skariel** [comment]
# works!
